[package]
name = "grib_parse"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grib = "0.4.3"
grib-build = "0.3.0"